services:
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    restart: unless-stopped
    env_file: ../../.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONF_DIR}/lidarr:/config
      - ${DATA_DIR}/downloads:/downloads
      - ${DATA_DIR}/media:/media
    labels:
      traefik.enable: true
      traefik.http.routers.lidarr.rule: Host(`lidarr.${DOMAIN}`)
