services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    env_file: ../.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/media:/media
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.${DOMAIN}`)

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    restart: unless-stopped
    env_file: ../.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONFIG_PATH}/sonarr-anime:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/media:/media
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr-anime.rule: Host(`sonarr-anime.${DOMAIN}`)