services:
  whisparr:
    container_name: whisparr
    image: ghcr.io/hotio/whisparr
    restart: unless-stopped
    env_file: ../../.env
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - ${CONF_DIR}/whisparr:/config
      - ${DATA_DIR}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.whisparr.rule: Host(`whisparr.${DOMAIN}`)