services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    env_file: ../../.env
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
      VERSION: docker
    volumes:
      - ${CONF_DIR}/plex:/config
      - ${DATA_DIR}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.plex.rule: Host(`plex.${DOMAIN}`)
      traefik.http.routers.plex.entrypoints: websecure
      traefik.http.services.plex.loadbalancer.server.port: 32400
