services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
    env_file: ../.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      VERSION: docker
      PLEX_CLAIM: ${PLEX_CLAIM}
    volumes:
      - ${CONF_DIR}/plex:/config
      - ${DATA_DIR}/media:/media
    networks:
      - frontend
    labels:
      traefik.enable: true
      traefik.http.routers.plex.rule: Host(`plex.${DOMAIN}`)
