services:
  tailscale:
    image: tailscale/tailscale:latest
    container_name: tailscale
    cap_add:
      - NET_ADMIN
      - NET_RAW
    env_file: ../../.env
    environment:
      TS_AUTH_ONCE: true
      TS_AUTHKEY: ${TS_AUTHKEY}
      TS_HOSTNAME: "homelab"
      TS_STATE_DIR: /var/lib/tailscale
      TS_SERVE_CONFIG: |
        {
          "TCP": {
            "443": { "HTTPS": { "InsecureSkipVerify": true, "HTTP1": true, "ForwardAddr": "traefik:443" } },
            "80":  { "TCP":   { "ForwardAddr": "traefik:80" } }
          }
        }
    volumes:
      - tailscale_data:/var/lib/tailscale
      - ./tailscale/data:/var/lib/tailscale:rw
      # Makes the tailscale socket (defined above) available to other services.
      - ./tailscale:/var/run/tailscale
      - /dev/net/tun:/dev/net/tun

volumes:
  tailscale_data:
    driver: local