services:
  traefik:
    container_name: "traefik"
    image: "traefik:latest"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    networks:
      - frontend
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      traefik.enable: true
      traefik.http.routers.dashboard.rule: Host(`dashboard.${DOMAIN}`)
      traefik.http.routers.dashboard.entrypoints: web
      traefik.http.services.dashboard.loadbalancer.server.port: 8080
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  traefik-whoami:
    container_name: "traefik-whoami"
    image: "traefik/whoami:latest"
    networks:
      - frontend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
