services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --experimental.localPlugins.authentik-forwardauth.modulename=github.com/fareedmurtaza/traefik-forward-authentik
      - --api.dashboard=true
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.ak-forwardauth.forwardauth.address=http://authentik-server:9000/outpost.goauthentik.io/auth/traefik
      - traefik.http.middlewares.ak-forwardauth.forwardauth.trustForwardHeader=true
      - traefik.http.middlewares.ak-forwardauth.forwardauth.authResponseHeaders=X-authentik-username,X-authentik-email
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - backend
      - frontend
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    depends_on:
      - authentik-server

  traefik-whoami:
    image: traefik/whoami:latest
    container_name: traefik-whoami
    labels:
      - traefik.enable=true
      - traefik.http.routers.whoami.rule=Host(`whoami.local`)
      - traefik.http.routers.whoami.entrypoints=web
      - traefik.http.routers.whoami.middlewares=ak-forwardauth
      - traefik.http.services.whoami.loadbalancer.server.port=80
    networks:
      - backend
