services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    env_file: ../.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - ${RADARR_PORT:-7878}:7878
    volumes:
      - ${CONFIG_PATH}/radarr:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/movies:/movies
    labels:
      traefik.enable: true
      traefik.port: ${RADARR_PORT:-7878}
      traefik.frontend.rule: Host:radarr.${DOMAIN}

  radarr-anime:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-anime
    restart: unless-stopped
    env_file: ../.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    ports:
      - ${RADARR_ANIME_PORT:-7979}:7878
    volumes:
      - ${CONFIG_PATH}/radarr-anime:/config
      - ${DATA_PATH}/downloads:/downloads
      - ${DATA_PATH}/movies-anime:/movies
    labels:
      traefik.enable: true
      traefik.port: ${RADARR_ANIME_PORT:-7979}
      traefik.frontend.rule: Host:radarr-anime.${DOMAIN}