services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /config:/config
      - ../data/movies:/movies
      - ../data/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped