global:
  checkNewVersion: true
  sendAnonymousUsage: false

log:
  level: INFO

entryPoints:
  web:
    address: :80
  websecure:
    address: :443

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false