services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    env_file: ../../.env
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - ${CONF_DIR}/sonarr:/config
      - ${DATA_DIR}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr.rule: Host(`sonarr.${DOMAIN}`)

  sonarr-anime:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-anime
    restart: unless-stopped
    env_file: ../../.env
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ${CONF_DIR}/sonarr-anime:/config
      - ${DATA_DIR}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.sonarr-anime.rule: Host(`sonarr-anime.${DOMAIN}`)