services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    env_file: ../../.env
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - ${CONF_DIR}/bazarr:/config
      - ${DATA_DIR}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr.rule: Host(`bazarr.${DOMAIN}`)

  bazarr-anime:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr-anime
    restart: unless-stopped
    env_file: ../../.env
    environment:
      PGID: ${PGID}
      PUID: ${PUID}
      TZ: ${TZ}
    volumes:
      - ${CONF_DIR}/bazarr-anime:/config
      - ${DATA_DIR}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.bazarr-anime.rule: Host(`bazarr-anime.${DOMAIN}`)